"""
setup.py — first-time configuration wizard.

Run this before starting the server for the first time:
    python setup.py

It will ask you a few questions and write a .env file for you.
Re-run it anytime to update your config.
"""

import os
from pathlib import Path

ENV_PATH = Path(".env")
ENV_EXAMPLE_PATH = Path(".env.example")


def read_existing_env() -> dict:
    """Parse existing .env into a dict so we can pre-fill answers."""
    if not ENV_PATH.exists():
        return {}
    result = {}
    for line in ENV_PATH.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, value = line.partition("=")
            result[key.strip()] = value.strip()
    return result


def ask(prompt: str, default: str = "", secret: bool = False) -> str:
    """Ask a question and return the answer (or default if blank)."""
    if default and secret:
        display_default = f"****{default[-4:]}" if len(default) > 4 else "****"
        hint = f" [{display_default}]"
    elif default:
        hint = f" [{default}]"
    else:
        hint = ""

    answer = input(f"  {prompt}{hint}: ").strip()
    return answer if answer else default


def write_env(values: dict) -> None:
    """Write all key=value pairs to .env."""
    lines = ["# Generated by setup.py — edit manually if needed\n"]
    for key, value in values.items():
        lines.append(f"{key}={value}\n")
    ENV_PATH.write_text("".join(lines))


def main():
    print("\n" + "═" * 52)
    print("  Business Audit API — Setup Wizard")
    print("═" * 52 + "\n")

    existing = read_existing_env()
    config = {}

    print("Step 1 — Server config")
    config["PORT"] = ask("Port", existing.get("PORT", "8000"))

    print("\nStep 2 — OpenAI")
    print("  Get your key at: https://platform.openai.com/api-keys")
    config["OPENAI_API_KEY"] = ask(
        "API key", existing.get("OPENAI_API_KEY", ""), secret=True
    )
    config["MODEL_NAME"] = ask(
        "Model name (gpt-4o-mini is cheapest)",
        existing.get("MODEL_NAME", "gpt-4o-mini"),
    )

    print("\nStep 3 — Storage")
    config["DATABASE_URL"] = ask(
        "SQLite file path", existing.get("DATABASE_URL", "./audit.db")
    )
    config["TEMP_DIR"] = ask(
        "Temp PDF folder", existing.get("TEMP_DIR", "./temp_reports")
    )

    print("\nStep 4 — Logging")
    config["LOG_LEVEL"] = ask(
        "Log level (DEBUG/INFO/WARNING)", existing.get("LOG_LEVEL", "INFO")
    )

    write_env(config)
    print("\n✓ .env written successfully.")
    print("\nNext steps:")
    print("  1. Install dependencies:  pip install -r requirements.txt")
    print("  2. Start the server:      python main.py")
    print("  3. Open in browser:       http://127.0.0.1:8000/api/v1/health\n")


if __name__ == "__main__":
    main()